application:
  version: 0.0.1
  title: salary-keeper

spring:
  profiles:
    active: local

--- # local
spring:
  datasource:
    platform: h2
    url: jdbc:h2:~/data/salary-keeper
    username: sa
    sql-script-encoding: UTF-8
    initialization-mode: always
    data: classpath:db/data.sql
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: trace
